name: CI/CD Innovatech - Backend

on:
  push:
    branches: [ "deploy" ]

jobs:
  build-push-deploy-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar credenciales AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login en Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build imagen Backend y push a ECR
      run: |
        aws ecr describe-repositories --repository-names innovatech_backend || aws ecr create-repository --repository-name innovatech_backend
        
        docker build -t innovatech_backend .
        docker tag innovatech_backend:latest ${{ secrets.ECR_REPO_URL_BACKEND }}:latest
        docker push ${{ secrets.ECR_REPO_URL_BACKEND }}:latest

    - name: Desplegar Backend vía SSM
      run: |
        aws ssm send-command \
          --instance-ids ${{ secrets.EC2_BACKEND_INSTANCE_ID }} \
          --document-name "AWS-RunShellScript" \
          --comment "Actualizar backend Innovatech" \
          --parameters '{"commands":[
            "set -e",
            "aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}",
            "docker pull ${{ secrets.ECR_REPO_URL_BACKEND }}:latest",
            "docker stop backend || true",
            "docker rm backend || true",
            "docker run -d --name backend -p 8080:3001 ${{ secrets.ECR_REPO_URL_BACKEND }}:latest"
          ]}' \
          --output text
